version: "3"

services:
  github_app_postgres:
    container_name: github_app_postgres
    image: postgres:11-alpine
    env_file:
      - ./.env
    ports:
      - "5432:5432"

  github_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: github_app
    env_file:
      - ./.env
    volumes:
      - ./:/app
    working_dir: /app
    command: /bin/sh -c
      "/usr/local/bin/mix deps.get;
       /usr/local/bin/mix deps.compile;
       tail -f /dev/null";
    ports:
      - "4000:4000"
      - "4001:4001"
    depends_on:
      - github_app_postgres
